ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB1
    baudrate: 128000
    frame_id: laser_frame
    reversion: false
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: true
    angle_min: -180.0
    angle_max: 180.0
    range_min: 0.12
    range_max: 12.0
