ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB1
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 128000           # หัวใจสำคัญของ X4 คือ 128000
    lidar_type: 1              # 1 = TYPE_TRIANGLE
    device_type: 0             # 0 = SERIAL
    sample_rate: 5             # 5kHz ตามสเปกในรูป (5000 Hz)
    abnormal_check_count: 8    # เพิ่มเป็น 8 เพื่อยืดเวลาให้รอบหมุนคงที่
    fixed_resolution: true
    reversion: true            # True สำหรับการหมุนสแกน 360 องศาเต็มวงของ X4
    inverted: true             # True สำหรับลำดับมุมตามเข็ม/ทวนเข็มของ X4
    auto_reconnect: true
    isSingleChannel: true      # X4 เป็น single channel
    intensity: false
    intensity_bit: 0
    support_motor_dtr: true    # เปิด DTR สำหรับควบคุมมอเตอร์
    angle_max: 180.0           # -180 ถึง +180 องศา (360 องศารอบตัว)
    angle_min: -180.0
    range_max: 10.0            # 10 เมตรตามสเปก
    range_min: 0.32            # 0.32 เมตร (ครอบคลุมเสา 4 มุมที่ระยะ 27.8 ซม. + ระยะเผื่อ ปลอดภัย 100%)
    frequency: 7.0             # 6-12 Hz แนะนำตั้งที่ 7.0
    invalid_range_is_inf: false
    debug: false
